mybatis:
  type-aliases-package: "com.diflows.backend.model"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/diflows?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true"
    username: root
    password: root
  redis:
    host: "127.0.0.1"
    port: 6379